# Generated by Django 3.2.8 on 2021-10-15 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_etudiant_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Etudiant',
        ),
    ]
