# Generated by Django 3.2.8 on 2021-10-15 11:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Epreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=50, verbose_name='Nom')),
                ('description', models.CharField(max_length=50)),
                ('ponderation', models.FloatField(verbose_name='Maxima')),
                ('dateCreation', models.DateField(auto_now_add=True, verbose_name='Créée le')),
                ('duree', models.DurationField(default=datetime.timedelta(seconds=7200), verbose_name='Durée')),
            ],
        ),
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lastname', models.CharField(max_length=50)),
                ('login', models.CharField(blank=True, max_length=50, null=True)),
                ('pwd', models.CharField(blank=True, default='123456789', max_length=50, null=True)),
                ('email', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Questionaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('contenu', models.TextField()),
                ('ponderation', models.FloatField()),
                ('corrige', models.TextField()),
                ('idEpreuve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.epreuve')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationEpreuve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateEpreuve', models.DateTimeField(auto_now_add=True)),
                ('validation', models.BooleanField()),
                ('Epreuve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.epreuve')),
                ('Etudiant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.etudiant')),
            ],
        ),
        migrations.CreateModel(
            name='Reponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('pointsObtenus', models.FloatField()),
                ('idQuestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.questionaire')),
            ],
        ),
    ]
