# Generated by Django 3.2.8 on 2021-10-15 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validationepreuve',
            name='Etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='quizzes.etudiant'),
        ),
        migrations.AlterUniqueTogether(
            name='validationepreuve',
            unique_together={('Epreuve', 'Etudiant')},
        ),
        migrations.RemoveField(
            model_name='validationepreuve',
            name='id',
        ),
    ]
