# Generated by Django 3.2.8 on 2021-10-15 14:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20211015_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='validationepreuve',
            name='id',
            field=models.IntegerField(default=django.utils.timezone.now, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='validationepreuve',
            name='Etudiant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizzes.etudiant'),
        ),
        migrations.AlterUniqueTogether(
            name='validationepreuve',
            unique_together={('id', 'Epreuve', 'Etudiant')},
        ),
    ]
