# Generated by Django 3.2.8 on 2021-10-17 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_auto_20211017_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epreuve',
            name='dateCreation',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Créée le'),
        ),
    ]
