# Generated by Django 3.2.8 on 2021-10-24 07:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0002_alter_reponse_pointsobtenus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponse',
            name='idQuestion',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, to='quizzes.questionaire', verbose_name='Question'),
            preserve_default=False,
        ),
    ]
