# Generated by Django 3.2.8 on 2021-10-17 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_alter_epreuve_datecreation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='epreuve',
            name='dateCreation',
            field=models.DateTimeField(verbose_name='Créée le'),
        ),
    ]
