# Generated by Django 3.2.8 on 2021-10-15 14:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0003_auto_20211015_1607'),
    ]

    operations = [
        migrations.RenameField(
            model_name='validationepreuve',
            old_name='Etudiant',
            new_name='etudiant',
        ),
        migrations.AddField(
            model_name='validationepreuve',
            name='epreuve',
            field=models.ForeignKey(db_column='epreuve', default=django.utils.timezone.now, on_delete=django.db.models.deletion.DO_NOTHING, to='quizzes.epreuve'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='validationepreuve',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='validationepreuve',
            name='Epreuve',
        ),
        migrations.RemoveField(
            model_name='validationepreuve',
            name='id',
        ),
    ]
