# Generated by Django 3.2.8 on 2021-10-15 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0004_auto_20211015_1634'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cotation',
        ),
    ]
